services:
  # Go Backend Application Service
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: kredit-plus-api
    volumes:
      - ../config.json:/app/config.json:ro
    ports:
      - "4000:4000" # adjust according to your settings in config.json
    depends_on:
      - otel-collector
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network: {}