version: '3.8'

name: 'xyz'
services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.126.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.69.0
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"   # Jaeger UI
      - "14250:14250"   # Jaeger model.proto
      - "14268:14268"   # Jaeger HTTP thrift spans
      - "14269:14269"   # Admin port

  redis:
    container_name: redis-xyz
    image: redis:alpine3.18
    ports:
      - 6379:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"